import { Bird } from "@/types/bird";
import {
  ImageRecord,
  ImageReviewStatus,
  ImageSpec,
  ImageVariant,
} from "@/types/image";
import { supabaseServerClient } from "@/lib/supabaseServerClient";
import { getBirdById, updateBird } from "@/lib/birdService";
import { AI_MODEL_IMAGE, SUPABASE_IMAGE_BUCKET } from "@/lib/config";

const VARIANT_SPECS: ImageSpec[] = [
  { style_family: "scientific", variant: "main_habitat" },
  { style_family: "scientific", variant: "standing_clean" },
  { style_family: "scientific", variant: "flight_clean" },
  { style_family: "iconic", variant: "fixed_pose_icon_v1" },
];

const REQUIRED_IMAGE_VARIANTS: ImageVariant[] = [
  "main_habitat",
  "fixed_pose_icon_v1",
];

function buildStoragePath(bird: Bird, spec: ImageSpec) {
  const timestamp = Date.now();
  return `${bird.slug}/${spec.variant}-${timestamp}.placeholder.txt`;
}

async function uploadPlaceholderImage(bird: Bird, spec: ImageSpec) {
  const path = buildStoragePath(bird, spec);
  const encoder = new TextEncoder();
  const payload = encoder.encode(
    `Placeholder for ${bird.slug} ${spec.variant} generated by ${AI_MODEL_IMAGE}`
  );

  const { error } = await supabaseServerClient.storage
    .from(SUPABASE_IMAGE_BUCKET)
    .upload(path, payload, { upsert: true, cacheControl: "3600" });

  if (error) {
    throw error;
  }

  return `${SUPABASE_IMAGE_BUCKET}/${path}`;
}

export async function generateImagesForBird(
  bird: Bird
): Promise<{ bird: Bird; images: ImageRecord[] }> {
  if (bird.status !== "text_approved") {
    throw new Error("Images can only be generated when the bird has text_approved status.");
  }

  const createdImages: ImageRecord[] = [];

  for (const spec of VARIANT_SPECS) {
    const storagePath = await uploadPlaceholderImage(bird, spec);

    const { data, error } = await supabaseServerClient
      .from("images")
    .insert({
      entity_type: "bird",
      entity_id: bird.id,
      style_family: spec.style_family,
      variant: spec.variant,
      storage_path: storagePath,
      review_status: "draft",
      version: `${AI_MODEL_IMAGE}:${spec.variant}`,
    })
      .select("*")
      .single();

    if (error || !data) {
      throw error ?? new Error("Failed to create image record.");
    }

    createdImages.push(data);
  }

  const updatedBird = await updateBird({ id: bird.id, status: "images_generated" });

  return { bird: updatedBird, images: createdImages };
}

export async function listImagesForBird(birdId: string): Promise<ImageRecord[]> {
  const { data, error } = await supabaseServerClient
    .from("images")
    .select("*")
    .eq("entity_type", "bird")
    .eq("entity_id", birdId)
    .order("variant", { ascending: true });

  if (error) {
    throw error;
  }

  return data ?? [];
}

function extractBucketPath(storagePath: string) {
  const [bucket, ...rest] = storagePath.split("/");
  return { bucket, path: rest.join("/") };
}

export async function getSignedImageUrl(storagePath: string) {
  const { bucket, path } = extractBucketPath(storagePath);

  if (!bucket || !path) {
    return null;
  }

  const { data, error } = await supabaseServerClient.storage
    .from(bucket)
    .createSignedUrl(path, 60 * 5);

  if (error || !data?.signedUrl) {
    return null;
  }

  return data.signedUrl;
}

async function advanceBirdIfImagesApproved(birdId: string) {
  const { data, error } = await supabaseServerClient
    .from("images")
    .select("review_status, variant")
    .eq("entity_type", "bird")
    .eq("entity_id", birdId);

  if (error) {
    throw error;
  }

  const images = (data ?? []) as ImageRecord[];

  if (images.length === 0) {
    return;
  }

  const approvalByVariant = new Map<ImageVariant, ImageReviewStatus>();
  images.forEach((image) => {
    approvalByVariant.set(image.variant, image.review_status);
  });

  const requiredApproved = REQUIRED_IMAGE_VARIANTS.every(
    (variant) => approvalByVariant.get(variant) === "approved"
  );

  if (!requiredApproved) {
    return;
  }

  const bird = await getBirdById(birdId);

  if (!bird) {
    return;
  }

  if (bird.status === "images_approved" || bird.status === "published") {
    return;
  }

  await updateBird({ id: birdId, status: "images_approved" });
}

export async function updateImageReviewStatus(
  imageId: string,
  status: ImageReviewStatus
): Promise<ImageRecord> {
  const { data, error } = await supabaseServerClient
    .from("images")
    .update({
      review_status: status,
      updated_at: new Date().toISOString(),
    })
    .eq("id", imageId)
    .select("*")
    .single();

  if (error || !data) {
    throw error ?? new Error("Unable to update image status.");
  }

  await advanceBirdIfImagesApproved(data.entity_id);

  return data;
}

export async function requestImageReview(
  birdId: string,
  imageId: string,
  comment: string
): Promise<ImageRecord> {
  const trimmedComment = comment.trim();

  if (!trimmedComment) {
    throw new Error("Please add a short note before requesting changes.");
  }

  const { data: existing, error: existingError } = await supabaseServerClient
    .from("images")
    .select("entity_id")
    .eq("id", imageId)
    .maybeSingle();

  if (existingError) {
    throw existingError;
  }

  if (!existing) {
    throw new Error("Image not found.");
  }

  if (existing.entity_id !== birdId) {
    throw new Error("Image does not belong to this bird.");
  }

  const { data, error } = await supabaseServerClient
    .from("images")
    .update({
      review_status: "reviewed",
      review_comment: trimmedComment,
      updated_at: new Date().toISOString(),
    })
    .eq("id", imageId)
    .select("*")
    .single();

  if (error || !data) {
    throw error ?? new Error("Unable to save the image review request.");
  }

  return data;
}
